/*
 * Copyright MapStruct Authors.
 *
 * Licensed under the Apache License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
package org.mapstruct;

import java.lang.annotation.Annotation;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import org.mapstruct.control.MappingControl;
import org.mapstruct.factory.Mappers;

import static org.mapstruct.NullValueCheckStrategy.ON_IMPLICIT_CONVERSION;
import static org.mapstruct.SubclassExhaustiveStrategy.COMPILE_ERROR;

/**
 * Marks an interface or abstract class as a mapper and activates the generation of a implementation of that type via
 * MapStruct.
 *
 * <p>
 * <strong>Example 1:</strong> Creating mapper
 * </p>
 * <pre><code class='java'>
 * &#64;Mapper
 * public interface CarMapper {
 *     CarDto toCarDto(Car source);
 * }
 * </code></pre>
 * <p>
 * <strong>Example 2:</strong> Use additional mappers with parameters {@link #uses()}, {@link #componentModel()}
 * and {@link #injectionStrategy()}
 * </p>
 * <pre><code class='java'>
 * // we have MarkMapper (map field "mark" to field "name" to upper case)
 * &#64;Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
 * public class MarkMapper {
 *     public String mapMark(String mark) {
 *         return mark.toUpperCase();
 *     }
 * }
 * // we have CarMapper
 * &#64;Mapper(
 *      componentModel = MappingConstants.ComponentModel.SPRING,
 *      uses = MarkMapper.class,
 *      injectionStrategy = InjectionStrategy.CONSTRUCTOR)
 * public interface CarMapper {
 *     &#64;Mapping(target = "name", source = "mark")
 *     CarDto convertMap(CarEntity carEntity);
 * }
 * </code></pre>
 * <pre><code class='java'>
 * // generates
 * &#64;Component
 * public class CarMapperImpl implements CarMapper {
 *     private final MarkMapper markMapper;
 *     &#64;Autowired
 *     public CarMapperImpl(MarkMapper markMapper) {
 *         this.markMapper = markMapper;
 *     }
 *     &#64;Override
 *     public CarDto convertMap(CarEntity carEntity) {
 *         if ( carEntity == null ) {
 *             return null;
 *         }
 *         CarDto carDto = new CarDto();
 *         carDto.setName( markMapper.mapMark( carEntity.getMark() ) );
 *         return carDto;
 *     }
 * }
 * </code></pre>
 *
 * @author Gunnar Morling
 * @see Javadoc
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.CLASS)
public @interface Mapper {

    /**
     * Other mapper types used by this mapper. May be hand-written classes or other mappers generated by MapStruct. No
     * cycle between generated mapper classes must be created.
     *
     * @return The mapper types used by this mapper.
     */
    Class<?>[] uses() default { };

    /**
     * Package where MapStruct can discover existing mappers.
     *
     * @return The package where MapStruct can discover existing mappers.
     */
    String usesPackage() default "";

    // ... other attributes ...
}