language: java
install: true
script: mvn clean install -DprocessorIntegrationTest.toolchainsFile=etc/toolchains-travis-jenkins.xml -B -V

matrix:
  include:
  - jdk: oraclejdk8
    after_success:
      - mvn jacoco:report && bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    dist: trusty
  - jdk: openjdk11
    # Only run the processor and its dependencies
    # The integration tests are using the maven toolchain and that is not yet ready for Java 11
    # There is an issue with the documentation so skip it
    script: mvn -B -V clean install -pl processor -am
  - jdk: openjdk13
    # Only run the processor and its dependencies
    # The integration tests are using the maven toolchain and that is not yet ready for Java 11
    # There is an issue with the documentation so skip it
    script: mvn -B -V clean install -pl processor -am
    # Only run the processor and its dependencies
    # The integration tests are using the maven toolchain and that is not yet ready for Java EA
    # There is an issue with the documentation so skip it
  - jdk: openjdk-ea
    script: mvn -B -V clean install -pl processor -am
  allow_failures:
    - jdk: openjdk-ea
deploy:
  provider: script
  script: "test ${TRAVIS_TEST_RESULT} -eq 0 && mvn -s etc/travis-settings.xml -DskipTests=true -DskipDistribution=true deploy"
  skip_cleanup: true
  on:
    repo: mapstruct/mapstruct
    branch: master
    jdk: oraclejdk8

sudo: required
cache:
  directories:
  - $HOME/.m2
