language: java
jdk:
  - oraclejdk8
install: true
script: mvn clean install -DprocessorIntegrationTest.toolchainsFile=etc/toolchains-travis-jenkins.xml -B -V

sudo: false
cache:
  directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
